"""Build the downloadable example bundle and the page that shows what is in it.

Two outputs, both derived from `get-examples/` and both checked into the
repository:

    documentation/get-examples.zip        what a reader downloads
    documentation/guide/example-bundle.html   the same files, readable in a browser

Run it after changing anything under `get-examples/`:

    python3 tools/build_bundle.py

`--check` rebuilds into memory and compares against what is committed, exiting
non-zero on any difference. That is what CI runs, and it is the only thing
stopping the download from drifting a version behind the page describing it.
"""

import argparse
import hashlib
import html
import os
import sys
import zipfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLE = os.path.join(REPO, "get-examples")
ZIP_PATH = os.path.join(REPO, "documentation", "get-examples.zip")
PAGE_PATH = os.path.join(REPO, "documentation", "guide", "example-bundle.html")

# Fixed so the archive is byte-identical between rebuilds. zipfile otherwise
# stamps each entry with its file's mtime, which makes every checkout produce a
# different zip and defeats the --check comparison.
FIXED_TIMESTAMP = (2026, 1, 1, 0, 0, 0)

LANGUAGE = {".py": "python", ".toml": "toml", ".csv": None}

# A base graph is 100+ lines of `0,1,1`. Enough to see the shape and the header,
# not so much that it buries the configs below it.
CSV_PREVIEW_LINES = 12


def is_shipped(relative):
    """Whether a path under `get-examples/` belongs in the download.

    `output/` is where a reader's own runs land, and this script is normally run
    by someone who has been running the examples — so everything under it is
    excluded except the `.gitkeep` that carries the empty directory into the
    archive. Without that, the published zip would ship whoever built it last.
    """
    if relative.startswith("output/"):
        return relative == "output/.gitkeep"
    return not (relative.startswith("__pycache__/") or relative.endswith(".pyc"))


def bundle_files():
    """Every file the bundle ships, as paths relative to `get-examples/`.

    Sorted, so the archive's entry order and the page's section order do not
    depend on how the filesystem happens to enumerate a directory.
    """
    found = []
    for directory, _subdirs, names in os.walk(BUNDLE):
        for name in names:
            full = os.path.join(directory, name)
            relative = os.path.relpath(full, BUNDLE).replace(os.sep, "/")
            if is_shipped(relative):
                found.append(relative)
    found.sort()
    return found


def build_zip(files):
    """The archive's bytes, unpacking to a `get-examples/` directory."""
    import io

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for relative in files:
            info = zipfile.ZipInfo(f"get-examples/{relative}", FIXED_TIMESTAMP)
            # 0o644, and the high half marks it a regular file — without this
            # entries unpack with whatever mode the running umask implies.
            info.external_attr = (0o100644 & 0xFFFF) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            with open(os.path.join(BUNDLE, relative), "rb") as handle:
                archive.writestr(info, handle.read())
    return buffer.getvalue()


def section(relative):
    """One file's section on the page: a heading and its contents."""
    extension = os.path.splitext(relative)[1]
    language = LANGUAGE.get(extension)

    with open(os.path.join(BUNDLE, relative), "r", encoding="utf-8") as handle:
        text = handle.read()

    note = ""
    if extension == ".csv":
        lines = text.splitlines()
        if len(lines) > CSV_PREVIEW_LINES:
            text = "\n".join(lines[:CSV_PREVIEW_LINES])
            note = (
                f'\n<div class="callout"><p>First {CSV_PREVIEW_LINES} lines of '
                f"{len(lines)}. Every remaining line is one more edge; download "
                f"the bundle for the whole file.</p></div>"
            )

    anchor = relative.replace(".", "-").replace("/", "-")
    opening = f'<pre><code class="language-{language}">' if language else "<pre><code>"
    return (
        f'<h2 id="{anchor}">{html.escape(relative)}</h2>\n'
        f"{opening}{html.escape(text)}</code></pre>{note}\n"
    )


def build_page(files):
    """The generated page's HTML.

    Empty files are in the archive but not on the page: `output/.gitkeep` exists
    to carry a directory, and has nothing to read.
    """
    readable = [f for f in files if os.path.getsize(os.path.join(BUNDLE, f)) > 0]
    sections = "\n".join(section(relative) for relative in readable)
    return f"""<!doctype html>
<!-- GENERATED by tools/build_bundle.py from get-examples/. Do not edit by hand:
     CI rebuilds this file and fails if it differs from what is committed. Change
     the files under get-examples/ and re-run the script instead. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Example Bundle · GET Docs</title>
<link rel="stylesheet" href="../assets/style.css">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><text y='26' font-size='26'>🧬</text></svg>">
</head>
<body data-page="guide/example-bundle.html">
<main>

<p class="page-kicker">Using GET</p>
<h1>The Example Bundle</h1>
<p class="lede">
  Every file in the download, readable here without unpacking it. These are the
  files themselves, not a description of them &mdash; the page is generated from
  the same directory the archive is built from.
</p>

<div class="tip">
  <b>Download it:</b> <a href="../get-examples.zip">get-examples.zip</a>. Unpack
  it, then follow the header in <code>python_from_config.py</code>. Run
  <code>01</code> through <code>04</code> as they are; <code>05</code> is the
  exercise and needs one block uncommented first.
</div>

{sections}
</main>
<script src="../assets/site.js"></script>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed outputs instead of writing them",
    )
    args = parser.parse_args()

    files = bundle_files()
    if not files:
        print(f"no files found under {BUNDLE}", file=sys.stderr)
        return 1

    archive = build_zip(files)
    page = build_page(files).encode("utf-8")

    if not args.check:
        with open(ZIP_PATH, "wb") as handle:
            handle.write(archive)
        with open(PAGE_PATH, "wb") as handle:
            handle.write(page)
        print(f"wrote {os.path.relpath(ZIP_PATH, REPO)} ({len(archive)} bytes)")
        print(f"wrote {os.path.relpath(PAGE_PATH, REPO)} from {len(files)} files")
        return 0

    stale = []
    for path, fresh in ((ZIP_PATH, archive), (PAGE_PATH, page)):
        try:
            with open(path, "rb") as handle:
                committed = handle.read()
        except FileNotFoundError:
            stale.append(f"{os.path.relpath(path, REPO)} is missing")
            continue
        if committed != fresh:
            stale.append(
                f"{os.path.relpath(path, REPO)} is stale "
                f"(committed {hashlib.sha256(committed).hexdigest()[:12]}, "
                f"rebuilt {hashlib.sha256(fresh).hexdigest()[:12]})"
            )

    for problem in stale:
        print(f"  {problem}")
    if stale:
        print("run: python3 tools/build_bundle.py")
        return 1

    print(f"bundle is current: {len(files)} files, zip and page both match")
    return 0


if __name__ == "__main__":
    sys.exit(main())
