#!/usr/bin/env python3
"""Generate `get`'s type stubs from the built extension module.

    maturin develop --release          # the stubs describe what is installed
    python3 tools/generate_stubs.py
    python3 tools/generate_stubs.py --check    # CI: fail if the tree is stale

PyO3 compiles each `#[pyclass]`'s `///` comments into `__doc__` and each method's
parameter names and defaults into `__text_signature__`. This reads both off the
imported module, so the stubs cannot drift from the code that produced them —
there is no second copy of a signature to keep in step.

**It preserves type annotations you add by hand, and that is the whole design.**
`__text_signature__` carries names and defaults but no types, so the generated
file starts untyped and is annotated by hand once. A regeneration that discarded
that work would make the tool unusable after its first run, so instead every
annotation in the existing file is read back and reapplied to the parameter it
belongs to. Add a parameter in Rust and it appears here unannotated; remove one
and its annotation goes with it; rename one and the annotation is dropped, which
is correct — the old name no longer describes anything.

Module-level `import` lines in the existing file are preserved the same way, so
`from typing import ...` written for a hand annotation survives.

**Standard library only, like everything else in `tools/`.** It does need the
module importable, which means building it first; `--check` is the same
generation compared against the tree rather than written to it.
"""

import argparse
import ast
import importlib
import sys
import types

DEFAULT_OUT = "python/get/__init__.pyi"

HEADER = '''"""Type stubs for `get`, generated by `tools/generate_stubs.py`.

Regenerate with `maturin develop --release && python3 tools/generate_stubs.py`.
Type annotations here are written by hand and survive regeneration; everything
else comes from the built module.
"""'''

# `#[staticmethod]` arrives as a plain `staticmethod`; the rest are the descriptor
# types CPython uses for methods defined in C.
CALLABLE_TYPES = (
    types.MethodDescriptorType,
    types.BuiltinFunctionType,
    types.WrapperDescriptorType,
    staticmethod,
    classmethod,
)


def parse_signature(text, receiver):
    """`__text_signature__` to an `ast.arguments`, or None if there isn't one.

    `receiver` is the name to give a leading `$self`/`$type`, or None for a
    static method.
    """
    if text is None:
        return None
    inner = text.strip()[1:-1].strip()
    for marker in ("$self", "$type"):
        if inner.startswith(marker):
            inner = inner[len(marker):]
            break
    else:
        # A constructor signature sits on the class and names no receiver.
        if receiver is not None:
            inner = ", " + inner if inner else ""
    if receiver is not None:
        inner = receiver + inner
    inner = inner.lstrip(", ")
    if receiver is not None and not inner.startswith(receiver):
        inner = receiver + (", " + inner if inner else "")
    try:
        tree = ast.parse(f"def _{'(' + inner + ')'}: ...")
    except SyntaxError:
        return None
    return tree.body[0].args


def all_args(args):
    return list(args.posonlyargs) + list(args.args) + list(args.kwonlyargs) + [
        a for a in (args.vararg, args.kwarg) if a is not None
    ]


def apply_annotations(args, saved):
    """Reapply saved annotations to the parameters that still carry those names."""
    for arg in all_args(args):
        text = saved.get(arg.arg)
        if text is not None:
            arg.annotation = ast.parse(text, mode="eval").body


def render_function(name, args, returns, decorators, indent):
    fn = ast.FunctionDef(
        name=name,
        args=args,
        body=[ast.Expr(value=ast.Constant(value=Ellipsis))],
        decorator_list=[ast.Name(id=d, ctx=ast.Load()) for d in decorators],
        returns=ast.parse(returns, mode="eval").body if returns else None,
        type_params=[],
    )
    ast.fix_missing_locations(fn)
    return [indent + line for line in ast.unparse(fn).splitlines()]


def render_docstring(obj, indent):
    doc = obj.__doc__
    if not doc:
        return []
    lines = doc.strip().splitlines()
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']
    out = [f'{indent}"""{lines[0]}']
    out += [indent + line if line else "" for line in lines[1:]]
    out.append(f'{indent}"""')
    return out


def render_class(cls, name, path, saved, depth):
    pad = "    " * depth
    body = "    " * (depth + 1)
    out = [f"{pad}class {name}:"]
    out += render_docstring(cls, body)

    # The constructor's signature is on the class; PyO3 leaves `__new__` generic.
    init = parse_signature(getattr(cls, "__text_signature__", None), "self")
    if init is not None:
        key = f"{path}.__init__"
        apply_annotations(init, saved.get(key, {}))
        out += render_function("__init__", init, saved.get(key, {}).get("return"), [], body)

    wrote = len(out) > 1
    for attr in sorted(cls.__dict__):
        if attr.startswith("__"):
            continue
        value = cls.__dict__[attr]
        key = f"{path}.{attr}"
        if isinstance(value, type):
            # A complex-enum variant is a nested class, and carries the
            # constructor a caller actually reaches for.
            out.append("")
            out += render_class(value, attr, key, saved, depth + 1)
        elif isinstance(value, types.GetSetDescriptorType):
            args = ast.parse("def _(self): ...").body[0].args
            out += render_function(attr, args, saved.get(key, {}).get("return"), ["property"], body)
        elif isinstance(value, CALLABLE_TYPES):
            static = isinstance(value, staticmethod)
            target = value.__func__ if static else value
            args = parse_signature(
                getattr(target, "__text_signature__", None), None if static else "self"
            )
            if args is None:
                args = ast.parse("def _(self, *args, **kwargs): ...").body[0].args
            apply_annotations(args, saved.get(key, {}))
            out += render_function(
                attr, args, saved.get(key, {}).get("return"),
                ["staticmethod"] if static else [], body,
            )
        else:
            continue
        wrote = True

    if not wrote:
        out.append(f"{body}...")
    return out


def read_existing(path):
    """Annotations and imports from an existing stub, keyed by dotted path."""
    try:
        source = open(path, encoding="utf-8").read()
    except FileNotFoundError:
        return {}, []
    tree = ast.parse(source)
    saved = {}
    imports = []

    def walk(node, prefix):
        for child in node.body:
            if isinstance(child, ast.ClassDef):
                walk(child, f"{prefix}{child.name}.")
            elif isinstance(child, ast.FunctionDef):
                entry = {}
                for arg in all_args(child.args):
                    if arg.annotation is not None:
                        entry[arg.arg] = ast.unparse(arg.annotation)
                if child.returns is not None:
                    entry["return"] = ast.unparse(child.returns)
                if entry:
                    saved[f"{prefix}{child.name}"] = entry
            elif isinstance(child, (ast.Import, ast.ImportFrom)) and node is tree:
                imports.append(ast.unparse(child))

    walk(tree, "")
    return saved, imports


def generate(module, saved, imports):
    lines = [HEADER, ""]
    if imports:
        lines += sorted(set(imports)) + [""]
    names = list(getattr(module, "__all__", None) or sorted(
        n for n in dir(module) if not n.startswith("_")
    ))
    lines.append("__all__ = [" + ", ".join(repr(n) for n in names) + "]")
    for name in names:
        value = getattr(module, name)
        if not isinstance(value, type):
            continue
        lines.append("")
        lines += render_class(value, name, name, saved, 0)
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"output path (default {DEFAULT_OUT})")
    parser.add_argument(
        "--check", action="store_true",
        help="compare against the file instead of writing it; exit 1 if they differ",
    )
    args = parser.parse_args()

    try:
        module = importlib.import_module("get")
    except ImportError as err:
        sys.exit(f"cannot import `get` — build it first with `maturin develop --release`: {err}")

    saved, imports = read_existing(args.out)
    text = generate(module, saved, imports)

    if args.check:
        try:
            current = open(args.out, encoding="utf-8").read()
        except FileNotFoundError:
            sys.exit(f"{args.out} does not exist; run this without --check")
        if current != text:
            sys.exit(f"{args.out} is out of date — regenerate with tools/generate_stubs.py")
        print(f"{args.out} is up to date")
        return

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
