#!/usr/bin/env python3
"""Generate `get`'s type stubs from the built extension module.

    maturin develop --release          # the stubs describe what is installed
    python3 tools/generate_stubs.py
    python3 tools/generate_stubs.py --check    # CI: fail if the tree is stale

PyO3 compiles each `#[pyclass]`'s `///` comments into `__doc__` and each method's
parameter names and defaults into `__text_signature__`. This reads both off the
imported module, so the stubs cannot drift from the code that produced them —
there is no second copy of a signature to keep in step.

**It preserves type annotations and docstrings you add by hand, and that is the
whole design.**
`__text_signature__` carries names and defaults but no types, so the generated
file starts untyped and is annotated by hand once. A regeneration that discarded
that work would make the tool unusable after its first run, so instead every
annotation in the existing file is read back and reapplied to the parameter it
belongs to. Add a parameter in Rust and it appears here unannotated; remove one
and its annotation goes with it; rename one and the annotation is dropped, which
is correct — the old name no longer describes anything.

Module-level `import` lines are preserved the same way, so `from typing import
...` written for a hand annotation survives.

Hand-written **docstrings** are preserved only where the module supplies none.
PyO3 0.27 drops `///` comments on complex-enum variants and their fields — 48 of
`get`'s 102 documentable items, including every `FitnessConfig` variant — so for
those the stub is the only place documentation can live. Where the module does
supply a docstring it wins, because that one comes from the Rust and is the copy
that cannot go stale; a hand-written docstring displaced that way is reported
rather than dropped silently.

**Standard library only, like everything else in `tools/`.** It does need the
module importable, which means building it first; `--check` is the same
generation compared against the tree rather than written to it.

**Python 3.9 or newer**, for `ast.unparse`. That is a floor on running this
script, not on the package: `pyproject.toml` supports 3.8 and the wheel is built
against the 3.8 ABI. CI runs the check in its own job for exactly this reason —
the wheel-building job uses 3.8.
"""

import argparse
import ast
import importlib
import sys
import types

if not hasattr(ast, "unparse"):
    sys.exit(
        f"tools/generate_stubs.py needs Python 3.9 or newer for `ast.unparse`; "
        f"this is {sys.version.split()[0]}. The package still supports 3.8 — "
        f"only this script does not."
    )

DEFAULT_OUT = "python/get/__init__.pyi"

HEADER = '''"""Type stubs for `get`, generated by `tools/generate_stubs.py`.

Regenerate with `maturin develop --release && python3 tools/generate_stubs.py`.
Type annotations here are written by hand and survive regeneration; everything
else comes from the built module.
"""'''

# `#[staticmethod]` arrives as a plain `staticmethod`; the rest are the descriptor
# types CPython uses for methods defined in C.
CALLABLE_TYPES = (
    types.MethodDescriptorType,
    types.BuiltinFunctionType,
    types.WrapperDescriptorType,
    staticmethod,
    classmethod,
)


def parse_signature(text, receiver):
    """`__text_signature__` to an `ast.arguments`, or None if there isn't one.

    `receiver` is the name to give a leading `$self`/`$type`, or None for a
    static method.
    """
    if text is None:
        return None
    inner = text.strip()[1:-1].strip()
    for marker in ("$self", "$type"):
        if inner.startswith(marker):
            inner = inner[len(marker):]
            break
    else:
        # A constructor signature sits on the class and names no receiver.
        if receiver is not None:
            inner = ", " + inner if inner else ""
    if receiver is not None:
        inner = receiver + inner
    inner = inner.lstrip(", ")
    if receiver is not None and not inner.startswith(receiver):
        inner = receiver + (", " + inner if inner else "")
    try:
        tree = ast.parse(f"def _{'(' + inner + ')'}: ...")
    except SyntaxError:
        return None
    return tree.body[0].args


def all_args(args):
    return list(args.posonlyargs) + list(args.args) + list(args.kwonlyargs) + [
        a for a in (args.vararg, args.kwarg) if a is not None
    ]


def apply_annotations(args, saved):
    """Reapply saved annotations to the parameters that still carry those names."""
    for arg in all_args(args):
        text = saved.get(arg.arg)
        if text is not None:
            arg.annotation = ast.parse(text, mode="eval").body


def render_function(name, args, returns, decorators, indent, doc=None):
    fn = ast.FunctionDef(
        name=name,
        args=args,
        body=[ast.Expr(value=ast.Constant(value=Ellipsis))],
        decorator_list=[ast.Name(id=d, ctx=ast.Load()) for d in decorators],
        returns=ast.parse(returns, mode="eval").body if returns else None,
        type_params=[],
    )
    ast.fix_missing_locations(fn)
    lines = [indent + line for line in ast.unparse(fn).splitlines()]
    if doc:
        # `ast.unparse` renders the body as a trailing `...`; the docstring goes
        # above it, at the body's indent.
        lines[-1:-1] = render_doc_lines(doc, indent + "    ")
    return lines


def render_doc_lines(doc, indent):
    lines = doc.strip().splitlines()
    if len(lines) == 1:
        return [f'{indent}"""{lines[0]}"""']
    out = [f'{indent}"""{lines[0]}']
    out += [indent + line if line else "" for line in lines[1:]]
    out.append(f'{indent}"""')
    return out


def pick_doc(obj, key, saved_docs, displaced):
    """The module's docstring if it has one, else whatever the stub carried."""
    own = (obj.__doc__ or "").strip()
    kept = saved_docs.get(key)
    if own:
        if kept and kept.strip() != own:
            displaced.append(key)
        return own
    return kept


def render_class(cls, name, path, saved, docs, displaced, depth):
    pad = "    " * depth
    body = "    " * (depth + 1)
    out = [f"{pad}class {name}:"]
    doc = pick_doc(cls, path, docs, displaced)
    if doc:
        out += render_doc_lines(doc, body)

    # The constructor's signature is on the class; PyO3 leaves `__new__` generic.
    init = parse_signature(getattr(cls, "__text_signature__", None), "self")
    if init is not None:
        key = f"{path}.__init__"
        apply_annotations(init, saved.get(key, {}))
        out += render_function(
            "__init__", init, saved.get(key, {}).get("return"), [], body, docs.get(key)
        )

    wrote = len(out) > 1
    for attr in sorted(cls.__dict__):
        if attr.startswith("__"):
            continue
        value = cls.__dict__[attr]
        key = f"{path}.{attr}"
        if isinstance(value, type):
            # A complex-enum variant is a nested class, and carries the
            # constructor a caller actually reaches for.
            out.append("")
            out += render_class(value, attr, key, saved, docs, displaced, depth + 1)
        elif isinstance(value, types.GetSetDescriptorType):
            args = ast.parse("def _(self): ...").body[0].args
            out += render_function(
                attr, args, saved.get(key, {}).get("return"), ["property"], body,
                pick_doc(value, key, docs, displaced),
            )
        elif isinstance(value, CALLABLE_TYPES):
            static = isinstance(value, staticmethod)
            target = value.__func__ if static else value
            args = parse_signature(
                getattr(target, "__text_signature__", None), None if static else "self"
            )
            if args is None:
                args = ast.parse("def _(self, *args, **kwargs): ...").body[0].args
            apply_annotations(args, saved.get(key, {}))
            out += render_function(
                attr, args, saved.get(key, {}).get("return"),
                ["staticmethod"] if static else [], body,
                pick_doc(target, key, docs, displaced),
            )
        else:
            continue
        wrote = True

    if not wrote:
        out.append(f"{body}...")
    return out


def read_existing(path):
    """Annotations, docstrings and imports from an existing stub, by dotted path."""
    try:
        source = open(path, encoding="utf-8").read()
    except FileNotFoundError:
        return {}, {}, []
    tree = ast.parse(source)
    saved = {}
    docs = {}
    imports = []

    def walk(node, prefix):
        for child in node.body:
            if isinstance(child, ast.ClassDef):
                key = f"{prefix}{child.name}"
                doc = ast.get_docstring(child, clean=True)
                if doc:
                    docs[key] = doc
                walk(child, f"{key}.")
            elif isinstance(child, ast.FunctionDef):
                doc = ast.get_docstring(child, clean=True)
                if doc:
                    docs[f"{prefix}{child.name}"] = doc
                entry = {}
                for arg in all_args(child.args):
                    if arg.annotation is not None:
                        entry[arg.arg] = ast.unparse(arg.annotation)
                if child.returns is not None:
                    entry["return"] = ast.unparse(child.returns)
                if entry:
                    saved[f"{prefix}{child.name}"] = entry
            elif isinstance(child, (ast.Import, ast.ImportFrom)) and node is tree:
                imports.append(ast.unparse(child))

    walk(tree, "")
    return saved, docs, imports


def generate(module, saved, docs, imports, displaced):
    lines = [HEADER, ""]
    if imports:
        lines += sorted(set(imports)) + [""]
    names = list(getattr(module, "__all__", None) or sorted(
        n for n in dir(module) if not n.startswith("_")
    ))
    lines.append("__all__ = [" + ", ".join(repr(n) for n in names) + "]")
    for name in names:
        value = getattr(module, name)
        if not isinstance(value, type):
            continue
        lines.append("")
        lines += render_class(value, name, name, saved, docs, displaced, 0)
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"output path (default {DEFAULT_OUT})")
    parser.add_argument(
        "--check", action="store_true",
        help="compare against the file instead of writing it; exit 1 if they differ",
    )
    args = parser.parse_args()

    try:
        module = importlib.import_module("get")
    except ImportError as err:
        sys.exit(f"cannot import `get` — build it first with `maturin develop --release`: {err}")

    saved, docs, imports = read_existing(args.out)
    displaced = []
    text = generate(module, saved, docs, imports, displaced)

    # A hand-written docstring only loses to one the module now supplies. Say so:
    # silently discarding it is how the stub stops being worth hand-editing.
    for key in displaced:
        print(f"note: {key} now has a docstring in the module; the stub's was dropped",
              file=sys.stderr)

    if args.check:
        try:
            current = open(args.out, encoding="utf-8").read()
        except FileNotFoundError:
            sys.exit(f"{args.out} does not exist; run this without --check")
        if current != text:
            sys.exit(f"{args.out} is out of date — regenerate with tools/generate_stubs.py")
        print(f"{args.out} is up to date")
        return

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
